### ISSUE TITLE
Add support for IE11

### ISSUE THREAD

**Issue by francbelak** [ChrisRu/es6-router#7]
Hey @ChrisRu 

would you mind adding support for IE11? The only issue is with new Event in navigate

`if (path !== 'error') {
      window.dispatchEvent(new Event('hashchange'));
 }`

I would appreciate if you could use the polyfill https://stackoverflow.com/a/26596324. If you do not want to have it as a part of your project it is not a big deal for us. I can make the polyfill part of our project setups. (In this case it would be cool if you would mention that IE11 support is given with this polyfill in the README to help other developers avoid spending time searching for it and debugging :))

Cheers,
Franky

**Comment by ChrisRu** [comment]
Ah yes, did not realise. Thanks.
Has been fixed in version 3.1.3
